# Task 1: Define Single and Multi-Dimensional Numpy Arrays

In [210]:
import os

In [211]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax

import numpy as np

In [212]:
# Let's define a one-dimensional array

list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [213]:
# Let's create a numpy array from the list "list_1"

my_numpy_array = np.array(list_1)
my_numpy_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [214]:
type(my_numpy_array)

numpy.ndarray

In [215]:
# Multi-dimensional (Matrix definition)

my_matrix = np.array([[2, 5, 8], [7, 3, 6]])
my_matrix

array([[2, 5, 8],
       [7, 3, 6]])

In [216]:
# Challenge 1

challenge_matrix = np.array([[3, 7, 9, 3], [4, 3, 2, 2]])
challenge_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# Task 2: Leverage Numpy Built-In Methods and Functions

In [217]:
# "rand()" uniform distribution between 0 and 1

x = np.random.rand(20)
x

array([0.53315869, 0.66908147, 0.27297   , 0.97693965, 0.39808064,
       0.42690486, 0.63326833, 0.72515236, 0.09567833, 0.26798267,
       0.01977219, 0.26232368, 0.67147632, 0.75247839, 0.88564627,
       0.2706325 , 0.87936036, 0.51670562, 0.115345  , 0.95849525])

In [218]:
# you can create a matrix of random number as well

x = np.random.rand(3, 3)
x

array([[0.77253536, 0.88115377, 0.75834568],
       [0.15123048, 0.51660665, 0.7581775 ],
       [0.29557577, 0.25540699, 0.64789655]])

In [219]:
# "randint" is used to generate random integers between upper and lower bounds

x = np.random.randint(1, 50)
x

40

In [220]:
# "randint" can be used to generate a certain number of random itegers as follows

x = np.random.randint(1, 100, 15)
x

array([72, 84, 14, 71, 43, 55, 98, 15, 63, 81, 97, 99, 73, 27, 57])

In [221]:
# np.arange creates an evenly spaced values within a given interval

x = np.arange(1, 50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [222]:
# create a diagonal of ones and zeros everywhere else

x = np.eye(7)
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [223]:
# Matrix of ones

x = np.ones((7, 7))
x

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [224]:
# Array of zeros

x = np.zeros(8)
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [225]:
# Challenge 2

def make_array(x):
    array = np.random.randint(0, x, 10)
    return array

In [226]:
# x = int(input("Please enter a positive integer value"))
print("Choose an integer with a value of 0 or higher: ")
x = input()
x = int(x)
print(make_array(x))

Choose an integer with a value of 0 or higher: 
6
[0 2 3 0 1 5 2 5 4 0]


# Task 3: Perform Mathematical Operations in Numpy

In [227]:
# np.arange() returns an evenly spaced values within a given interval

x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [228]:
y = np.arange(1, 10)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [229]:
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [230]:
square_array = x ** 2
square_array

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [231]:
square_root = np.sqrt(square_array)
square_root

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [232]:
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [233]:
# Challenge 3
import math

x = [5, 7, 20]
y = [9, 15, 4]

print(math.dist(x, y))

18.33030277982336


In [234]:
x_array = np.array(x)
y_array = np.array(y)

print(x_array)
print(y_array)

distance = math.sqrt(((x_array[0] - y_array[0]) **2) + ((x_array[1] - y_array[1]) **2) + ((x_array[2] - y_array[2] **2)))
distance

print(math.dist(x_array, y_array))

[ 5  7 20]
[ 9 15  4]
18.33030277982336


In [235]:
# answer needed

z = np.sqrt( x_array**2 + y_array**2)
z

array([10.29563014, 16.55294536, 20.39607805])

# Task 4: Performing Arrays Slicing and Indexing

In [236]:
my_numpy_array = np.array([3, 5, 6, 2, 8, 10, 20, 50])
my_numpy_array

array([ 3,  5,  6,  2,  8, 10, 20, 50])

In [237]:
# Access specific index from the numpy array

my_numpy_array[0]

3

In [238]:
# Starting from the first index 0 up until and NOT including the last element

my_numpy_array[0:3]

array([3, 5, 6])

In [239]:
# Broadcasting, altering several values in a numpy array at once

my_numpy_array[0:4] = 7
my_numpy_array

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [240]:
# Let's define a two dimensional nnumpy array

matrix = np.random.randint(1, 10, (4, 4))
matrix

array([[9, 8, 9, 3],
       [3, 1, 7, 3],
       [1, 5, 7, 9],
       [8, 8, 5, 2]])

In [241]:
# Get a row from a matrix

matrix[0]

array([9, 8, 9, 3])

In [242]:
# Get one element

matrix[0][2]

9

In [243]:
# Challenge 4

x = np.array([[2, 30, 20, -2, -4], [3, 4, 40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [244]:
x[4][0:] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# Task 5: Perform Elements Selection(Conditional)

In [245]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[2, 1, 1, 4, 7],
       [8, 5, 9, 9, 8],
       [4, 4, 4, 8, 2],
       [5, 9, 4, 6, 1],
       [1, 3, 5, 1, 2]])

In [246]:
# filter based on greater than

new_matrix = matrix[ matrix > 5 ]
new_matrix

array([7, 8, 9, 9, 8, 8, 9, 6])

In [247]:
# filter odd elements only

new_matrix_odd = matrix[ matrix % 2 == 1 ]
new_matrix_odd

array([1, 1, 7, 5, 9, 9, 5, 9, 1, 1, 3, 5, 1])

In [248]:
# Challenge 5 In the following matrix, replace negative elements by 0 and replace odd elements with -2

x = np.array([[2, 30, 20, -2, -4], [3, 4, 40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37]])
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [13, 24, 22, 32, 37]])

In [249]:
a = 0
b = 0
for lst_array in x:
    for num in lst_array:
        if num < 0:
            x[a][b] = 0
        elif num % 2 == 1:
            x[a][b] = -2
        b += 1
    b = 0    
    a += 1
x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

In [250]:
# Instructor Answer

x = np.array([[2, 30, 20, -2, -4], [3, 4, 40, -3, -2], [-3, 4, -6, 90, 10], [25, 45, 34, 22, 12], [13, 24, 22, 32, 37]])
x

x[ x < 0] = 0
x[ x % 2 == 1] = -2

x

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# Task 6: Understanding Panda Fundamentals

In [251]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [252]:
import pandas as pd

In [253]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444], 'Bank Client Name':['Chanel', 
                                'Steve', 'Mitch', 'Ryan'], 'Net Worth [$]':[3500, 29000, 10000, 2000],
                                'Years with bank':[3, 4, 9, 5]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [254]:
type(bank_client_df)

pandas.core.frame.DataFrame

In [255]:
bank_client_df.head(1)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3

In [256]:
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [257]:
# Challenge 6
# A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
# Calculate the total value of the porfolio including all stocks

In [258]:
stock_portfolio = pd.DataFrame({'Security':['IBM', 'Volvo AB', 'Raytheon'], 'Stock Ticker':['IBM', 'VLVLY', 'RTX'], 'Shares':[75, 46, 52], 
                                'Price/Share':[138.33, 16.52, 95.71]})
stock_portfolio

Security Stock Ticker  Shares  Price/Share
0       IBM          IBM      75       138.33
1  Volvo AB        VLVLY      46        16.52
2  Raytheon          RTX      52        95.71

In [259]:
tote_ibm = stock_portfolio['Shares'][0] * stock_portfolio['Price/Share'][0]
tote_volv = stock_portfolio['Shares'][1] * stock_portfolio['Price/Share'][1]
tote_ray = stock_portfolio['Shares'][2] * stock_portfolio['Price/Share'][2]

print(tote_ibm)
print(tote_volv)
print(tote_ray)

tote_value = tote_ibm + tote_volv + tote_ray
print(tote_value)

10374.750000000002
759.92
4976.92
16111.590000000002


In [260]:
# Instructor's answer

stocks_dollar_value = stock_portfolio['Shares'] * stock_portfolio['Price/Share']
print(stocks_dollar_value)
print('-'*25)
stocks_dollar_value.sum()


0    10374.75
1      759.92
2     4976.92
dtype: float64
-------------------------


16111.590000000002

# Task 7: Pandas With CSV and HTML Data

In [261]:
! pip install html5lib

In [262]:
! pip install BeautifulSoup4

In [263]:
# Pandas is used to read a csv file and store data in a DataFrame

import os
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [264]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [265]:
# Challenge #7
# Write a code that uses Pandas to read tabular US retirement data
# You can use data from here: https://www.ssa.gov/oact/progdata/nra.html

In [266]:
retire_data = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html') # to read csv change to read_csv and use file name
retire_data[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# Task 8: Pandas Operations

In [267]:
# Let's deinfe a datafrom as follows:

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444], 'Bank Client Name':['Chanel', 
                                'Steve', 'Mitch', 'Ryan'], 'Net Worth [$]':[3500, 29000, 10000, 2000],
                                'Years with bank':[3, 4, 9, 5]})

bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [268]:
# Pick certain rows that satisfy a certain criteria

df_loyal = bank_client_df[ bank_client_df['Years with bank'] >= 5 ]
df_loyal

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [269]:
del bank_client_df[ 'Bank Client ID']
bank_client_df

Bank Client Name  Net Worth [$]  Years with bank
0           Chanel           3500                3
1            Steve          29000                4
2            Mitch          10000                9
3             Ryan           2000                5

In [270]:
# Challenge 8
# Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000
# What is the combined networth for all customers with 5000+ networth?

In [271]:
df_high_worth = bank_client_df[ bank_client_df['Net Worth [$]'] >= 5000 ]
df_high_worth

Bank Client Name  Net Worth [$]  Years with bank
1            Steve          29000                4
2            Mitch          10000                9

In [272]:
combined_net = df_high_worth['Net Worth [$]'].sum()
combined_net

39000

# Task 9: Pandas With Functions

In [273]:
# Let's define the dataframe as follows:

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444], 'Bank Client Name':['Chanel', 
                                'Steve', 'Mitch', 'Ryan'], 'Net Worth [$]':[3500, 29000, 10000, 2000],
                                'Years with bank':[3, 4, 9, 5]})

bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [274]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 

def networth_update(balance):
    return balance * 1.2

In [275]:
bank_client_df['Net Worth [$]'].apply(networth_update)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net Worth [$], dtype: float64

In [276]:
bank_client_df['Bank Client Name'].apply(len)

0    6
1    5
2    5
3    4
Name: Bank Client Name, dtype: int64

In [277]:
# Challenge #9
# Define a function that triples the stock prices(Net Worth) and adds $200
# Apply the function to the DataFrame
# Calculate the updated total networth of all clients combined

In [278]:
def windfall(balance):
    return balance * 3 + 200

In [279]:
bank_client_df['Net Worth [$]'].apply(windfall)

0    10700
1    87200
2    30200
3     6200
Name: Net Worth [$], dtype: int64

In [280]:
bank_client_df['Net Worth [$]'].apply(windfall).sum()

134300

# Task 10: Perform Sorting and Ordering in Pandas

In [281]:
# Let's define the dataframe as follows:

bank_client_df = pd.DataFrame({'Bank Client ID': [111, 222, 333, 444], 'Bank Client Name':['Chanel', 
                                'Steve', 'Mitch', 'Ryan'], 'Net Worth [$]':[3500, 29000, 10000, 2000],
                                'Years with bank':[3, 4, 9, 5]})

bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [282]:
# You can sort the values in the dataframe according to number of years with bank

bank_client_df.sort_values(by = 'Years with bank')

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

In [283]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True

bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
2             333            Mitch          10000                9
3             444             Ryan           2000                5

In [284]:
# Set inplace = True to ensure that change has taken place in memory 

bank_client_df.sort_values(by = 'Years with bank', inplace = True)
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             111           Chanel           3500                3
1             222            Steve          29000                4
3             444             Ryan           2000                5
2             333            Mitch          10000                9

# Task 11: Perform Concatenating and Merging with Pandas

In [285]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [286]:
df1 = pd.DataFrame({ 'A':['A0', 'A1', 'A2', 'A3'], 
                     'B':['B0', 'B1', 'B2', 'B3'],
                     'C':['C0', 'C1', 'C2', 'C3'],
                     'D':['D0', 'D1', 'D2', 'D3']},
                  index = [0, 1, 2, 3])

In [287]:
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [288]:
df2 = pd.DataFrame({ 'A':['A4', 'A5', 'A6', 'A7'], 
                     'B':['B4', 'B5', 'B6', 'B7'],
                     'C':['C4', 'C5', 'C6', 'C7'],
                     'D':['D4', 'D5', 'D6', 'D7']},
                  index = [4, 5, 6, 7])

In [289]:
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [290]:
df3 = pd.DataFrame({ 'A':['A8', 'A9', 'A10', 'A11'], 
                     'B':['B8', 'B9', 'B10', 'B11'],
                     'C':['C8', 'C9', 'C10', 'C11'],
                     'D':['D8', 'D9', 'D10', 'D11']},
                  index = [8, 9, 10,11])

In [291]:
df3

A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [292]:
pd.concat([df1, df2, df3])

A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# Task 12: Panda Project

<ul><li>Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5</li>
<li>Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10</li>
<li>Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers)</li>
<li>Concatenate both 'bank_df_1' and 'bank_df_2' dataframes</li>
<li>Merge client names and their newly added salary information using the 'Bank Client ID'</li>
<li>Let's assume that you became a new client to the bank</li>
<li>Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.</li>
<li>Add this new dataframe to the original dataframe 'bank_df_all'.</li></ul>

In [293]:
Bank_df_1 = pd.DataFrame({ 'Customer ID':[1, 2, 3, 4, 5,], 
                          'Customer First Name':['Sassy', 'Richy', 'Bogus', 'Leisure', 'Fat'],
                         'Customer Last Name':['Sally', 'Rich', 'Bonita', 'Larry', 'Frank']})
Bank_df_1

Customer ID Customer First Name Customer Last Name
0            1               Sassy              Sally
1            2               Richy               Rich
2            3               Bogus             Bonita
3            4             Leisure              Larry
4            5                 Fat              Frank

In [294]:
Bank_df_2 = pd.DataFrame({ 'Customer ID':[6, 7, 8, 9, 10], 
                          'Customer First Name':['Felonius', 'Kindly', 'Crashcart', 'Sporty', 'Viking'],
                         'Customer Last Name':['Felicia', 'Kendal', 'Carl', 'Sophie', 'Vic']})
Bank_df_2

Customer ID Customer First Name Customer Last Name
0            6            Felonius            Felicia
1            7              Kindly             Kendal
2            8           Crashcart               Carl
3            9              Sporty             Sophie
4           10              Viking                Vic

In [295]:
Bank_df_2 = pd.DataFrame({ 'Customer ID':[6, 7, 8, 9, 10], 
                          'Customer First Name':['Felonius', 'Kindly', 'Crashcart', 'Sporty', 'Viking'],
                         'Customer Last Name':['Felicia', 'Kendal', 'Carl', 'Sophie', 'Vic']})
Bank_df_2

Customer ID Customer First Name Customer Last Name
0            6            Felonius            Felicia
1            7              Kindly             Kendal
2            8           Crashcart               Carl
3            9              Sporty             Sophie
4           10              Viking                Vic

In [296]:
Salaries_df = pd.DataFrame({'Customer ID':[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                          'Customer Salary':[76000, 200000, 23000, 15000, 47000, 9000, 89000, 39000, 99000, 123000]}
                          )
Salaries_df

Customer ID  Customer Salary
0            1            76000
1            2           200000
2            3            23000
3            4            15000
4            5            47000
5            6             9000
6            7            89000
7            8            39000
8            9            99000
9           10           123000

In [297]:
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all

Customer ID Customer First Name Customer Last Name
0            1               Sassy              Sally
1            2               Richy               Rich
2            3               Bogus             Bonita
3            4             Leisure              Larry
4            5                 Fat              Frank
0            6            Felonius            Felicia
1            7              Kindly             Kendal
2            8           Crashcart               Carl
3            9              Sporty             Sophie
4           10              Viking                Vic

In [299]:
bank_df_all = bank_df_all.merge(Salaries_df, how='inner', on='Customer ID')
print(type(bank_df_all))

<class 'pandas.core.frame.DataFrame'>


In [300]:
new_client_df = pd.DataFrame({'Customer ID':[11], 'Customer First Name':['Yosemite'], 'Customer Last Name':['Sam'], 'Customer Salary':[67000]})
new_client_df

Customer ID Customer First Name Customer Last Name  Customer Salary
0           11            Yosemite                Sam            67000

In [301]:
bank_df_all = pd.concat([bank_df_all, new_client_df])
bank_df_all

Customer ID Customer First Name Customer Last Name  Customer Salary
0            1               Sassy              Sally            76000
1            2               Richy               Rich           200000
2            3               Bogus             Bonita            23000
3            4             Leisure              Larry            15000
4            5                 Fat              Frank            47000
5            6            Felonius            Felicia             9000
6            7              Kindly             Kendal            89000
7            8           Crashcart               Carl            39000
8            9              Sporty             Sophie            99000
9           10              Viking                Vic           123000
0           11            Yosemite                Sam            67000